spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
#    password: Bingo@2021
    timeout: 10s
    lettuce.pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      max-wait: -1ms
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://59.212.129.32:3000/radar?rewriteBatchedStatements=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: Taiji@2021
      validation-query: SELECT 1
      # 连接池大小根据实际情况调整
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
  kafka:
#    bootstrap-servers: 192.168.196.241:29092
    bootstrap-servers: 59.212.129.32:9092
    #bootstrap-servers: localhost:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: latest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      security:
        protocol: SASL_PLAINTEXT
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="ax_hlx" password="ax_hlx";'
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false
logging:
#  basePath: /home/project/demo/logs
#  config: classpath:log-config/logback-spring.xml
  level:
    root: info
    cn.com.taiji: info
taiji:
  kafka.consumer:
    tianao_original:
      topic: 'hlx_ax_original_ais'
      group: '202003070914'
    count_topic:
      topic: 'topic'
      group: 'group'
file:
  time: 5
  num: 500
  sourcePath:  /home/topic
  targetPath:  /app/vsftpd/zww-gaw-bianjie/bianjie/test/

ftp:
  host: 10.184.14.137
  username: hazd_ztry
  password: HAZD@Ztry
  port: 10021
  upload:
    filename: \
    filepath: \
  download:
    filename: \20230410_ZP.zip
    filepath: \
    localpath: d:\gyq\

bj:
  num: 5000000

wrj:
  filePath: /app/wrj/ydyp/海事边检任务
#  filePath: C:\haiguan
es:
  hosts: 74.10.28.65:9201,74.10.28.66:9200,74.10.28.66:9201,74.10.28.66:9202,74.10.28.67:9200,74.10.28.67:9201,74.10.28.67:9202,74.10.28.68:9200,74.10.28.68:9201,74.10.28.68:9202,74.10.28.69:9200,74.10.28.69:9201,74.10.28.69:9202
  username: ax_seat
  password: ax_seat
  connectTimeout: 100
  maxConnection: 100